### ISSUE TITLE
Unable to add C/R pair as a prereq for an activity

### ISSUE THREAD

**Issue by mvignal** [droundy/progressions-website#5] opened 2019-02-10 16:57 UTC
When I try to add the pair the page reloads but it doesn't show up.

**Comment by droundy** [comment] 2019-02-12 00:49
Turns out that it is getting added properly, but not displayed properly, so far as I can tell.  You just see the base concept.

**Comment by mvignal** [comment] 2019-02-15 15:45
It looks like this is still an issue. This issue is slowing me down more than any others, so if we can prioritize it that would be very helpful.

**Comment by droundy** [comment] 2019-02-16 00:53
I've just enabled and confirmed that prereqs should show up (both in different courses and in the same course).  I'll close this now, if you can come up with an example where it doesn't show up, please let me know, ideally with the specific activity and C/R.  It's possible there is a corner case that I've missed.

**Closed as completed by droundy** 2019-02-16 00:53 UTC
